development:
  adapter: postgresql
  database: reviewmybook_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: reviewmybook_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: reviewmybook_production
  pool: 5
  timeout: 5000